linters:
  enable:
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - revive
    - gofmt
    - goimports
    - misspell
    - unparam
    - nakedret
    - whitespace
    - errcheck

linters-settings:
  revive:
    rules:
      - name: exported
        severity: warning
        disabled: true
      - name: package-comments
        disabled: true
      - name: unused-parameter
        disabled: true

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
